[Interface]
PrivateKey = uMigyeayvASJsDWxA6uW50d2EFh5lexfyB5bRpaBxnQ=
Address = 10.66.66.2/32

[Peer]
PublicKey = 3w3KKVmdzCiaOj1EWO3xLc0LoNpo5LK4av1lb8XtQEM=
PresharedKey = DBJaHOETbFsoLYXl7hBvzCtxD7J+JTUpXPF0Rwrs00E=
Endpoint = 66.94.105.155:64422
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
